#!/usr/bin/env node

var args = process.argv.slice(2);

if(args.length === 1) {
  main(args[0], true);
} else {
  console.error('Usage: tulun <file>');
  process.exit();
}

function main(f, again) {
  var fs = require('fs');

  fs.readFile(f, 'utf8', function(err, data) {
    if(err) {
      if(again) {
        main(f + '.tul', false)
      } else {
        if(err.errno === -2) {
          console.error('That program doesn\'t exist!');
        } else if (err.errno === -21) {
          console.error('Can\'t run a directory!');
        } else {
          console.error(err);
        }

        process.exit();
      }
    } else {
      try {
        require('./dist/run').run(data.toString());
      } catch(err) {
        console.error(err.stack);
      }
    }
  });
}
