<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tul</string>
	</array>
	<key>name</key>
	<string>Tulun (tlnccuwagnf)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(=|-)&gt;</string>
			<key>name</key>
			<string>meta.operator.tulun</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((?!-)(?&lt;=\W)|^)(true|false)(?!-)(?=\W)</string>
			<key>name</key>
			<string>constant.language.tulun</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([0-9]+(\.[0-9]+)?)</string>
			<key>name</key>
			<string>constant.numeric.tulun</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#</string>
			<key>end</key>
			<string>\#</string>
			<key>name</key>
			<string>comment.line.number-sign.tulun</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tulun</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tulun</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\()\s*(.*)\s*(\))(?= *\{)</string>
			<key>name</key>
			<string>other.argument-list.tulun</string>
		</dict>
		<dict>
			<key>match</key>
			<string>async\s(?=.*\{)</string>
			<key>name</key>
			<string>support.function.tulun</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((return|process|print-debug|Variable|print|concat|if|ifel|obj|array|loop|use|make|change|value|from|exists)\s*(?=\(|;|\s))|((?!\([$\w0-9-+=-]+)\s+(return|process|print-debug|Variable|print|concat|if|ifel|obj|array|loop|use|make|change|value|from|exists)\s+(?=([$\w0-9-+=-]+)+\)))</string>
			<key>name</key>
			<string>keyword.control.tulun</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((add|divide|minus|multiply|not|and|or|lt|gt|eq|is|\+|-|\/|\*|&lt;|&gt;|=)\s*(?=\(|;|\s))|((?!\([$\w0-9-+=-]+)\s+(add|divide|minus|multiply|not|and|or|lt|gt|eq|is|\+|-|\/|\*|&lt;|&gt;|=)\s+(?=([$\w0-9-+=-]+)+\)))</string>
			<key>name</key>
			<string>keyword.operator.tulun</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.tulun</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x[\da-fA-F]{2}|u[\da-fA-F]{4}|.)</string>
					<key>name</key>
					<string>constant.character.escape.tulun</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.tulun</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x[\da-fA-F]{2}|u[\da-fA-F]{4}|.)</string>
					<key>name</key>
					<string>constant.character.escape.tulun</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>([-_$a-zA-Z0-9][$\w0-9-+=\-]*\s*(?=\())|((?!\([$\w0-9-+=-]+)\s+([$\w0-9-+=-]+)\s+(?=([$\w0-9-+=-]+)+\)))</string>
			<key>name</key>
			<string>entity.name.function.tulun</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([-_$a-zA-Z0-9][$\w0-9-+=\-]*\s*(?=\(|(=|-)&gt;|\)|\s|;|\.))</string>
			<key>name</key>
			<string>variable.parameter.tulun</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.tulun</string>
	<key>uuid</key>
	<string>ddee081c-613a-495a-8a4d-848baa2dff73</string>
</dict>
</plist>
